name: release_static
run-name: Build static resources and publish with a release
on:
  push:
   tags:
     - '*'

jobs:

  release:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: control/test

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Create TGZ archive
        run: |
          tar -cvzf static.tgz static
      - name: Create ZIP archive
        run: |
          zip -r static.zip static
      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            control/test/static.tgz
            control/test/static.zip
